# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rootlayer/intent.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'rootlayer/intent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16rootlayer/intent.proto\x12\x0crootlayer.v1\"\xcc\x03\n\x06Intent\x12\x11\n\tintent_id\x18\x01 \x01(\t\x12\x11\n\tsubnet_id\x18\x02 \x01(\t\x12\x11\n\trequester\x18\x03 \x01(\t\x12\x14\n\x0csettle_chain\x18\x04 \x01(\t\x12\x13\n\x0bintent_type\x18\x05 \x01(\t\x12*\n\x06params\x18\x06 \x01(\x0b\x32\x1a.rootlayer.v1.IntentParams\x12\x13\n\x0bparams_hash\x18\x07 \x01(\x0c\x12\x12\n\ntips_token\x18\x08 \x01(\t\x12\x0c\n\x04tips\x18\t \x01(\t\x12\x14\n\x0c\x62udget_token\x18\n \x01(\t\x12\x0e\n\x06\x62udget\x18\x0b \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x0c \x01(\x03\x12\x19\n\x11intent_expiration\x18\r \x01(\x03\x12*\n\x06status\x18\x0e \x01(\x0e\x32\x1a.rootlayer.v1.IntentStatus\x12\x12\n\ncreated_at\x18\x0f \x01(\x03\x12\x11\n\tsignature\x18\x10 \x01(\x0c\x12\x19\n\x11pending_confirmed\x18\x11 \x01(\x08\x12\x1c\n\x14processing_confirmed\x18\x12 \x01(\x08\x12\x1c\n\x14validation_confirmed\x18\x13 \x01(\x08\"4\n\x0cIntentParams\x12\x12\n\nintent_raw\x18\x01 \x01(\x0c\x12\x10\n\x08metadata\x18\x02 \x01(\x0c*\xd3\x01\n\x0cIntentStatus\x12\x1d\n\x19INTENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15INTENT_STATUS_PENDING\x10\x01\x12\x19\n\x15INTENT_STATUS_CHAINED\x10\x02\x12\x1c\n\x18INTENT_STATUS_PROCESSING\x10\x03\x12\x1b\n\x17INTENT_STATUS_COMPLETED\x10\x04\x12\x19\n\x15INTENT_STATUS_EXPIRED\x10\x05\x12\x18\n\x14INTENT_STATUS_FAILED\x10\x06\x42\x44ZBgithub.com/pin-protocol/rootlayer/api/gen/go/rootlayer;rootlayerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rootlayer.intent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/pin-protocol/rootlayer/api/gen/go/rootlayer;rootlayerv1'
  _globals['_INTENTSTATUS']._serialized_start=558
  _globals['_INTENTSTATUS']._serialized_end=769
  _globals['_INTENT']._serialized_start=41
  _globals['_INTENT']._serialized_end=501
  _globals['_INTENTPARAMS']._serialized_start=503
  _globals['_INTENTPARAMS']._serialized_end=555
# @@protoc_insertion_point(module_scope)
